% This LilyPond file was generated by Rosegarden 15.12
\include "nederlands.ly"
\version "2.12.0"
\header {
    composer = "Anonimo"
    title = "Ay, linda amiga"
    tagline = "Created using Rosegarden 15.12 and LilyPond"
}
#(set-global-staff-size 18)
#(set-default-paper-size "a4")
global = { 
    \time 2/4
    
}
globalTempo = {
    \override Score.MetronomeMark #'transparent = ##t
    \tempo 4 = 80  
}
\score {
    << % common
        \context StaffGroup = "0" << 
            % Force offset of colliding notes in chords:
            \override Score.NoteColumn #'force-hshift = #1.0
            % Allow fingerings inside the staff (configured from export options):
            \override Score.Fingering #'staff-padding = #'()

            \context Staff = "track 1, S" << 
                \set Staff.instrumentName = \markup { \center-column { "S " } }
                \set Staff.midiInstrument = ""
                \set Score.skipBars = ##t
                \set Staff.printKeyCancellation = ##f
                \new Voice \global
                \new Voice \globalTempo

                \context Voice = "voice 1" {
                    % Segment: S
                    \override Voice.TextScript #'padding = #2.0
                    \override MultiMeasureRest #'expand-limit = 1
                    \once \override Staff.TimeSignature #'style = #'() 
                    \time 2/4
                    
                    \repeat volta 2 {
                        \clef "treble"
                        \key a \minor
                        a' 4 a' 8 [ c'' ]  |
                        b' 4 b' 8 [ g' ]  |
                        a' 4 g' 8 [ f' ]  |
                        e' 4 e'  |
%% 5
                        a' 4 a' 8 [ c'' ]  |
                        b' 8 [ b' b' g' ]  |
                        a' 4 g' 8 [ f' ]  |
                        e' 4 e' ^\markup { \large "Fine" } \bar "|." 
                        c'' 8 [ c'' b' g' ]  |
%% 10
                        a' 4 a'  |
                        c'' 8 [ c'' b' g' ]  |
                        a' 4. e' 8  |
                        a' 8 [ a' g' g' ]  |
                        e' 4 d'  |
%% 15
                        f' 8 [ a' g' f' ]  |
                        e' 4. e' 8  |
                        a' 8 [ a' g' g' ]  |
                        e' 4 d'  |
                        f' 8 [ a' a' gis' ]  |
%% 20
                        a' 2  |
                    } % close repeat
                } % Voice
                \new Lyrics \with {alignBelowContext="track 1"} \lyricsto "voice 1" \lyricmode {
                    \override LyricText #'self-alignment-X = #LEFT
                    \set ignoreMelismata = ##t
                     "Ay," "lin" "da-a" "mi" "ga" "que" "no" "vuel" "vo-a" "ver" "te," "cuer" "po" "ga" "rri" "do" "que" "me" "lle" "va-a" "la" "muer" "te." "No" "hay-a" "mor" "sin" "pe" "na," "pe" "na" "sin" "do" "lor," "ni" "do" "lor" "tan" "a" "gu" "do" "co" "mo-el" "del" "a" "mor," "ni" "do" "lor" "tan" "a" "gu" "do" "co" "mo-el" "del" "a" "mor." 
                    \unset ignoreMelismata
                } % Lyrics 1
                \new Lyrics \lyricsto "voice 1" \lyricmode {
                    \override LyricText #'self-alignment-X = #LEFT
                    \set ignoreMelismata = ##t
                     _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ "Le" "van" "te" "me" "ma" "dre" "al" "sa" "lir" "el" "sol," "fui" "por" "los" "cam" "pos" "ver" "des" "a" "bus" "car" "mi-a" "mor," "fui" "por" "los" "cam" "pos" "ver" "des" "a" "bus" "car" "mi-a" "mor." 
                    \unset ignoreMelismata
                } % Lyrics 2
            >> % Staff ends

            \context Staff = "track 2, A" << 
                \set Staff.instrumentName = \markup { \center-column { "A " } }
                \set Staff.midiInstrument = ""
                \set Score.skipBars = ##t
                \set Staff.printKeyCancellation = ##f
                \new Voice \global
                \new Voice \globalTempo

                \context Voice = "voice 2" {
                    % Segment: A
                    \override Voice.TextScript #'padding = #2.0
                    \override MultiMeasureRest #'expand-limit = 1
                    \once \override Staff.TimeSignature #'style = #'() 
                    \time 2/4
                    
                    \repeat volta 2 {
                        \clef "treble"
                        \key a \minor
                        a' 4 a' 8 [ a' ]  |
                        g' 4 g' 8 [ e' ]  |
                        f' 4 d' 8 [ f' ]  |
                        e' 4 e'  |
%% 5
                        a' 4 a' 8 [ a' ]  |
                        g' 8 [ g' g' e' ]  |
                        f' 4 d' 8 [ f' ]  |
                        e' 4 e' \bar "|." 
                        a' 8 [ a' g' g' ]  |
%% 10
                        e' 4 e'  |
                        a' 8 [ a' g' g' ]  |
                        e' 4. e' 8  |
                        f' 8 [ f' d' b ]  |
                        c' 4 d'  |
%% 15
                        d' 8 [ f' d' f' ]  |
                        e' 4. e' 8  |
                        c' 8 [ c' b b ]  |
                        c' 4 d'  |
                        f' 8 [ f' e' e' ]  |
%% 20
                        a' 2  |
                    } % close repeat
                } % Voice
            >> % Staff ends

            \context Staff = "track 3, T" << 
                \set Staff.instrumentName = \markup { \center-column { "T " } }
                \set Staff.midiInstrument = ""
                \set Score.skipBars = ##t
                \set Staff.printKeyCancellation = ##f
                \new Voice \global
                \new Voice \globalTempo

                \context Voice = "voice 3" {
                    % Segment: T
                    \override Voice.TextScript #'padding = #2.0
                    \override MultiMeasureRest #'expand-limit = 1
                    \once \override Staff.TimeSignature #'style = #'() 
                    \time 2/4
                    
                    \repeat volta 2 {
                        \clef "treble_8"
                        \key a \minor
                        c' 4 c' 8 [ c' ]  |
                        e' 4 e' 8 [ e' ]  |
                        d' 4 a 8 [ a ]  |
                        c' 4 c'  |
%% 5
                        c' 4 c' 8 [ c' ]  |
                        e' 8 [ e' e' e' ]  |
                        d' 4 a 8 [ a ]  |
                        c' 4 c' \bar "|." 
                        a 8 [ a b b ]  |
%% 10
                        c' 4 c'  |
                        a 8 [ a b b ]  |
                        c' 4. c' 8  |
                        c' 8 [ c' b g ]  |
                        g 4 f  |
%% 15
                        a 8 [ a a a ]  |
                        gis 4. gis 8  |
                        a 8 [ a b g ]  |
                        g 4 f  |
                        a 8 [ d' b b ]  |
%% 20
                        c' 2  |
                    } % close repeat
                } % Voice
            >> % Staff ends

            \context Staff = "track 4, B" << 
                \set Staff.instrumentName = \markup { \center-column { "B " } }
                \set Staff.midiInstrument = ""
                \set Score.skipBars = ##t
                \set Staff.printKeyCancellation = ##f
                \new Voice \global
                \new Voice \globalTempo

                \context Voice = "voice 4" {
                    % Segment: B
                    \override Voice.TextScript #'padding = #2.0
                    \override MultiMeasureRest #'expand-limit = 1
                    \once \override Staff.TimeSignature #'style = #'() 
                    \time 2/4
                    
                    \repeat volta 2 {
                        \clef "bass"
                        \key a \minor
                        a 4 a 8 [ a ]  |
                        e 4 e 8 [ e ]  |
                        d 4 d 8 [ d ]  |
                        a 4 a  |
%% 5
                        a 4 a 8 [ a ]  |
                        e 8 [ e e e ]  |
                        d 4 d 8 [ d ]  |
                        a 4 a \bar "|." 
                        a 8 [ a e e ]  |
%% 10
                        a 4 a  |
                        a 8 [ a e e ]  |
                        a 4. a 8  |
                        f 8 [ f g g ]  |
                        c 4 d  |
%% 15
                        d 8 [ d d d ]  |
                        e 4. e 8  |
                        f 8 [ f g g ]  |
                        c 4 d  |
                        d 8 [ d e e ]  |
%% 20
                        a 2  |
                    } % close repeat
                } % Voice
            >> % Staff (final) ends
        >> % StaffGroup 1

    >> % notes

    \layout {
        indent = 3.0\cm
        short-indent = 1.5\cm
        \context { \Staff \RemoveEmptyStaves }
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
%         \midi {
%         } 
} % score
