% This LilyPond file was generated by Rosegarden 25.06
\include "nederlands.ly"
\version "2.18.0"
\header {
    composer = "Evaristo San Miguel (letra) "
    subtitle = "Himno de la II República Española"
    title = "Himno de Riego"
    tagline = "Created using Rosegarden 25.06 and LilyPond"
}
#(set-global-staff-size 18)
#(set-default-paper-size "a4")
global = { 
    \time 6/8
    \skip 8 \skip 2.*24 
}
globalTempo = {
    \override Score.MetronomeMark.transparent = ##t
    \tempo 4 = 160  
}
\score {
    << % common
        % Force offset of colliding notes in chords:
        \override Score.NoteColumn.force-hshift = #1.0
        % Allow fingerings inside the staff (configured from export options):
        \override Score.Fingering.staff-padding = #'()

        \context Staff = "track 1" << 
            \set Staff.midiInstrument = "Acoustic Grand Piano"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \set Staff.autoBeaming = ##f % turns off all autobeaming

            \context Voice = "voice 0.0" {
                % Segment: -
                \override Voice.TextScript.padding = #2.0
                \override MultiMeasureRest.expand-limit = 1
                \partial 64*8
                \once \override Staff.TimeSignature.style = #'numbered 
                \time 6/8
                
                \clef "treble"
                \key a \major
                e' 8 ^\markup { \bold \large "Vivace" }  |
                cis'' 4. cis'' 8 ^( [ b' ) ] a'  |
                a' 4. gis' 4 e' 8  |
                d'' 4. d'' 8 ^( [ cis'' ) ] b'  |
%% 5
                e'' 4 ^( cis'' 8 ) a' 4 e' 8  |
                cis'' 4. cis'' 8 ^( [ b' ) ] a'  |
                a' 4. gis' 4 e' 8  |
                d'' 8 [ fis'' e'' ] d'' [ cis'' b' ]  |
                a' 4 r8 r4 a' 8  |
%% 10
                < fis'' d'' > 4. < d'' fis'' > 8 [ < e'' cis'' > ] < c'' dis'' >  |
                < cis'' e'' > 4. < cis'' e'' > 8 [ < d'' b' > ] < cis'' ais' >  |
                < b' d'' > 4. < d'' b' > 8 [ < cis'' a' > ] < b' gis' > -\tenuto  |
                < cis'' e'' > 4 < a' cis'' > 8 < e' a' > 4 < e' a' > 8  |
                < fis'' d'' > 4. < fis'' d'' > 8 [ < e'' cis'' > < dis'' c'' > ]  |
%% 15
                < e'' cis'' > 4. < cis'' e'' > 8 [ < d'' b' > < ais' cis'' > ]  |
                < d'' b' > 8 [ < d'' fis'' > < cis'' e'' > ] < d'' b' > [ < a' cis'' > < gis' b' > ]  |
                < e' a' > 4 r8 r4 < cis'' a' > 8  |
                < b' gis' > 4 < cis'' a' > 8 < d'' b' > 4 < e'' cis'' > 8  |
                < fis'' d'' > 4. < d'' b' > 4 < fis'' d'' > 8  |
%% 20
                < cis'' e'' > 4 < cis'' a' > 8 < d'' b' > 4 < gis' b' > 8  |
                < cis'' e'' > 4. r4 < cis'' a' > 8  |
                < b' gis' > 4 < cis'' a' > 8 < d'' b' > 4 < e'' cis'' > 8  |
                < fis'' d'' > 4. < d'' b' > 4 < fis'' d'' > 8  |
                < e'' cis'' > 8 [ < fis'' d'' > < e'' cis'' > ] < d'' b' > [ < cis'' a' > < b' gis' > ]  |
%% 25
                a' 4. r8 r4  |
                \bar "|."
            } % Voice

            % End of segment -

            % End voice 0

            % cycle 1   verse line 1
            \new Lyrics
            \with {alignBelowContext="track 1"}
            \lyricsto "voice 0.0" {
                \lyricmode {
                    \override LyricText.self-alignment-X = #LEFT
                    \set ignoreMelismata = ##t

                    % Segment "-": verse 1

                    %{   1 %}    Se
                    %{   2 %}    re nos _ y-a
                    %{   3 %}    le gres va
                    %{   4 %}    lien tes _ y-o
                    %{   5 %}    sa _ dos can
                    %{   6 %}    te mos _ sol
                    %{   7 %}    da dos el
                    %{   8 %}    him _ _ no a la
                    %{   9 %}    lid. De
                    %{  10 %}    nu es tros a
                    %{  11 %}    cen _ tos el
                    %{  12 %}    or be se ad
                    %{  13 %}    mi _ re y
                    %{  14 %}    en no so tros
                    %{  15 %}    mi re _ los
                    %{  16 %}    hi _ _ jos _ del
                    %{  17 %}    Cid. Sol
                    %{  18 %}    da _ dos la
                    %{  19 %}    pa tria nos
                    %{  20 %}    lla ma a la
                    %{  21 %}    lid, ju
                    %{  22 %}    re _ mos por
                    %{  23 %}    e lla ven
                    %{  24 %}    cer _ ven cer o mo
                    %{  25 %}    rir

                    \unset ignoreMelismata
                }
            } % Lyrics 

            % cycle 2   verse line 1
            \new Lyrics
            \lyricsto "voice 0.0" {
                \lyricmode {
                    \override LyricText.self-alignment-X = #LEFT
                    \set ignoreMelismata = ##t

                    % Segment "-": verse 2

                    %{   1 %}    El
                    %{   2 %}    mun do _ vio
                    %{   3 %}    nun ca mas
                    %{   4 %}    no ble o sa
                    %{   5 %}    di _ a ni
                    %{   6 %}    vio nun ca un
                    %{   7 %}    dia mas _
                    %{   8 %}    gran _ _ de el va
                    %{   9 %}    lor que-a
                    %{  10 %}    quel que in fla
                    %{  11 %}    ma _ dos nos
                    %{  12 %}    vi mos _ del
                    %{  13 %}    fue _ go exci
                    %{  14 %}    tar a _ _
                    %{  15 %}    Rie go _ de
                    %{  16 %}    Pa _ tri a el a
                    %{  17 %}    mor. _
                    %{  18 %}    _ _ _ _
                    %{  19 %}    _ _ _
                    %{  20 %}    _ _ _ _
                    %{  21 %}    _ _
                    %{  22 %}    _ _ _ _
                    %{  23 %}    _ _ _
                    %{  24 %}    _ _ _ _ _ _
                    %{  25 %}    _

                    \unset ignoreMelismata
                }
            } % Lyrics 

            % cycle 3   verse line 1
            \new Lyrics
            \lyricsto "voice 0.0" {
                \lyricmode {
                    \override LyricText.self-alignment-X = #LEFT
                    \set ignoreMelismata = ##t

                    % Segment "-": verse 3

                    %{   1 %}    La
                    %{   2 %}    trom pa _ gue
                    %{   3 %}    rre ra sus
                    %{   4 %}    e cos da al
                    %{   5 %}    vien _ to ho
                    %{   6 %}    rror al _ se
                    %{   7 %}    dien to, ya
                    %{   8 %}    ru _ ge el _ ca
                    %{   9 %}    ñón. Ya
                    %{  10 %}    Mar te _ sa
                    %{  11 %}    ñu do, la au
                    %{  12 %}    da cia _ pro
                    %{  13 %}    vo _ ca yel-in
                    %{  14 %}    ge nio _ in
                    %{  15 %}    vo ca _ de
                    %{  16 %}    nues _ _ tra _ na
                    %{  17 %}    ción. _
                    %{  18 %}    _ _ _ _
                    %{  19 %}    _ _ _
                    %{  20 %}    _ _ _ _
                    %{  21 %}    _ _
                    %{  22 %}    _ _ _ _
                    %{  23 %}    _ _ _
                    %{  24 %}    _ _ _ _ _ _
                    %{  25 %}    _

                    \unset ignoreMelismata
                }
            } % Lyrics 
        >> % Staff ends

    >> % notes

    \layout {
        \context { \Staff \RemoveEmptyStaves }
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
%         \midi {
%         } 
} % score
