% This LilyPond file was generated by Rosegarden 15.12
\include "nederlands.ly"
\version "2.12.0"
#(set-global-staff-size 18)
#(set-default-paper-size "a4")
global = { 
    \time 2/2
    \skip 1*86 \skip 4 
}
globalTempo = {
    \override Score.MetronomeMark #'transparent = ##t
    \tempo 4 = 145  
}
\score {
    << % common
        % Force offset of colliding notes in chords:
        \override Score.NoteColumn #'force-hshift = #1.0
        % Allow fingerings inside the staff (configured from export options):
        \override Score.Fingering #'staff-padding = #'()

        \context Staff = "track 1, Big Chords" << 
            \set Staff.instrumentName = \markup { \center-column { "Big Chords " } }
            \set Staff.midiInstrument = "Acoustic Grand Piano"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \set Staff.autoBeaming = ##f % turns off all autobeaming

            \context Voice = "voice 1" {
                % Segment: 
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1
                \once \override Staff.TimeSignature #'style = #'() 
                \time 2/2
                
                \clef "treble"
                < a d' > 4 _~ < a d' e' > _~ < d' f' e' > _~ < e' f' g' > _~  |
                < f' g' a' > 2 _~ < g' a' f' a' d' > 4 _~ < g' f' a' d' e' > _~  |
                < e' c' f' g' a' > 2 _~ < c' f' g' a' a' > _~  |
                < a' a' f' > 4 _~ < a' a' f' a' > _~ < f' bes' a' ees' > _~ < bes' a' ees' c'' > _~  |
%% 5
                < ees' d' f' c'' bes' > 2 _~ < d' f' c'' bes' a' > 4 _~ < g' e' bes' a' > _~  |
                < g' e' cis' e' a' > 1 _~  |
                                \once \override Staff.TimeSignature #'style = #'() 
                \time 2/4
                < e' a' > 2 _~  |
                                \once \override Staff.TimeSignature #'style = #'() 
                \time 2/2
                < e' a' a d' > 4 _~ < e' a' a d' e' > _~ < a d' f' e' > _~ < a d' f' e' g' > _~  |
                < d' f' a' e' g' > 2 _~ < e' g' f' d' a' a' > 4 _~ < e' f' d' a' a' g' > _~  |
%% 10
                < a' a' d' e' g' c' f' > 2 _~ < g' a' d' e' c' f' a' > 4 _~ < a' d' e' c' f' a' > _~  |
                < c' f' a' f' a' > 4 _~ < c' f' a' f' a' a' > _~ < f' a' bes' ees' a' > _~ < f' a' bes' ees' a' c'' > _~  |
                < a' bes' ees' c'' f' bes' d' > 4 _~ < bes' ees' f' bes' d' c'' > _~ < c'' a' f' bes' d' > _~ < e' a' f' bes' d' g' > _~  |
                < d' a' e' cis' g' e' a' > 1 _~  |
                < g' cis' e' a' d' > 4 _~ < cis' e' a' d' e' > _~ < e' f' a' d' e' > _~ < a' f' d' e' g' > _~  |
%% 15
                < e' f' d' g' a' f' c' > 4 _~ < f' d' g' a' f' c' > _~ < g' d' bes a' f' c' a' > _~ < d' bes a' f' c' a' g' > _~  |
                < a' a' d' bes g' d' f' > 2 _~ < g' a' d' bes d' f' a' > 4 _~ < a' d' bes d' f' a' > _~  |
                < d' f' a' f' a' > 4 _~ < d' f' a' f' a' a' > _~ < f' a' bes' ees' a' > _~ < f' a' bes' ees' a' c'' > _~  |
                < a' bes' ees' c'' bes' d' f' > 4 _~ < bes' ees' bes' d' f' c'' > _~ < c'' a' bes' d' f' > _~ < e' a' bes' d' f' g' > _~  |
                < f' a' e' a' c' g' f' > 1 _~  |
%% 20
                < g' c' f' a' d' a' > 4 _~ < c' f' d' a' a' a' > _~ < f' d'' d' a' a' a' > _~ < d' a' a' d'' a' a' > _~  |
                < a' g' bes d'' a' a' d' > 2. _~ < a' d'' a' d' f' g' bes > 4 _~  |
                < d'' a' g' bes d' d' f' > 4 _~ < g' bes d' f' a' d' f' > _~ < d' f' a' f' a' d' > _~ < d' f' f' a' > _~  |
                < d' e' f' f' a' > 1 _~  |
                < f' f' a' d' e' a' > 4 _~ < a' f' d' e' a' a' > _~ < f' a' d'' d' e' a' > _~ < d' e' a' a' a' d'' > _~  |
%% 25
                < a' a' d'' a' g' bes d' > 4 _~ < d'' a' bes d' a' g' > _~ < bes d' a' g' g c' e' > _~ < g' g c' e' a c' f' > _~  |
                < a a c' f' d' e' > 1 _~ 
                % warning: overlong bar truncated here |
                e' 2 _~ < a c' f' a d' > 4 _~ < c' f' a d' > _~  |
                < c' f' a d' a d' > 4 _~ < c' f' a d' a d' e' > _~ < c' f' a d' a d' e' f' > _~ < a d' g' a d' e' f' > _~  |
                < d' a' g' a d' e' f' > 2 _~ < g' a d' a' f' e' f' d' a' > 4 _~ < a' f' e' f' d' a' e' g' > _~  |
%% 30
                < a' a' f' f' d' e' g' c' a' > 2 _~ < a' f' f' d' a' a' e' g' c' > _~  |
                < e' g' a' c' f' a' f' a' > 4 _~ < a' c' f' a' g' f' a' a' > _~ < c' g' a' bes' f' a' f' a' ees' > _~ < f' a' a' bes' f' ees' c'' a' > _~  |
                < a' bes' f' ees' c'' a' bes' f' d' > 2 _~ < c'' a' f' ees' bes' f' d' a' > 4 _~ < f' ees' bes' f' d' a' e' g' > _~  |
                < bes' f' d' cis' e' a' a' e' g' > 1 _~  |
                < a' cis' e' a' e' g' d' > 4 _~ < e' g' cis' e' a' d' e' > _~ < g' f' cis' e' a' d' e' > _~ < g' f' cis' e' a' d' e' > _~  |
%% 35
                < d' c' f' g' a' e' f' > 2 _~ < e' a' c' f' g' a' f' d' bes > 4 _~ < a' c' f' g' a' f' bes g' d' > _~  |
                < f' a' a' f' bes g' d' d' a' > 2 _~ < a' a' f' bes d' a' a' g' d' > _~  |
                < d' f' a' a' g' d' f' a' > 4 _~ < a' d' f' a' g' f' a' a' > _~ < d' g' bes' f' a' f' a' a' ees' > _~ < f' a' a' a' bes' f' ees' c'' > _~  |
                < a' bes' f' ees' c'' bes' f' d' a' > 2 _~ < c'' a' f' ees' bes' f' d' a' > 4 _~ < f' ees' bes' f' d' a' e' g' > _~  |
                < bes' f' d' c' f' a' e' g' a' > 1 _~  |
%% 40
                < a' c' f' e' g' a' d' a' > 4 _~ < e' g' c' f' a' d' a' a' > _~ < g' d'' c' f' a' d' a' a' > _~ < c' f' a' d' a' a' a' d'' > _~  |
                < d' a' d' a' g' a' a' d'' bes > 2. _~ < d' a' d' a' g' a' a' d'' bes f' > 4 _~  |
                < a' g' a' d'' bes f' d' d' > 4 _~ < a' d'' g' bes f' d' d' f' > _~ < g' bes d' f' a' f' d' > _~ < bes d' a' d' f' f' f' > _~  |
                < f' d' a' d' e' f' f' > 2. _~ < d' a' d' e' f' f' > 4 _~  |
                < f' f' d' a' a' e' > 4 _~ < f' a' e' a' d' a' > _~ < f' a' e' a' d' a' d'' > _~ < a' e' d' a' a' a' d'' > _~  |
%% 45
                < d' a' d'' bes d' g' a' a' > 2 _~ < a' a' bes d' g' e' g c' > 4 _~ < bes d' g' g c' a c' e' f' > _~  |
                < c' e' a d' a c' f' g > 1 _~ 
                % warning: overlong bar truncated here |
                g 2 _~ < e' a d' a c' f' > _~  |
                < e' a d' a c' f' a d' > 4 _~ < e' a d' a c' f' a d' e' > _~ < a c' f' a d' a d' e' f' > _~ < g' f' a d' a d' e' f' > _~  |
                < f' g' a' a d' a d' e' f' > 2 _~ < f' g' a' a d' a d' e' f' f' a' d' > 4 _~ < a d' f' g' a' a d' e' f' a' d' > 64 _~ < a d' f' g' a' a d' e' f' a' d' e' g' > 4 _~ < g' a' a d' e' f' f' a' d' e' g' > 64 _~  |
%% 50
                < f' g' a' a' f' a' d' e' g' c' f' > 2 _~ < g' a' a' f' a' d' c' f' a' e' g' > _~  |
                < a' a' d' c' f' a' e' g' a' f' > 4 _~ < d' e' g' a' c' f' a' a' f' a' > _~ < g' ees' a' c' f' a' a' f' a' bes' > _~ < c'' ees' a' c' f' f' a' bes' a' a' > _~  |
                < a' f' a' bes' d' ees' c'' f' a' bes' > 2 _~ < f' a' ees' c'' f' a' bes' a' bes' d' > 4 _~ < a' ees' c'' f' a' bes' bes' d' e' a' g' > _~  |
                < ees' c'' f' bes' d' cis' e' e' a' g' a' > 1 _~  |
                < a' e' g' a' d' cis' e' > 4 _~ < a' e' g' a' d' cis' e' e' > _~ < e' g' d' cis' e' f' a' e' > _~ < d' cis' e' a' e' g' f' g' > _~  |
%% 55
                < g' g' d' e' f' c' a' f' a' > 2 _~ < g' g' d' e' f' c' a' f' a' a' bes d' > 4 _~ < d' e' f' c' a' f' a' g' a' bes d' g' > _~  |
                < g' g' f' c' a' a' a' bes d' d' f' > 2 _~ < f' c' a' a' d' f' g' a' bes d' a' > _~  |
                < a' bes d' g' a' a' f' a' d' f' > 4 _~ < bes d' a' g' a' a' f' a' d' f' > _~ < g' a' a' d' f' ees' a' f' bes' a' > _~ < c'' a' d' f' ees' f' bes' a' a' a' > _~  |
                < a' f' a' d' f' ees' c'' bes' bes' a' > 2 _~ < f' a' ees' c'' bes' bes' a' a' d' f' > 4 _~ < e' a' ees' c'' bes' bes' a' d' f' g' a' > _~  |
                < ees' c'' bes' e' d' f' c' f' a' g' a' > 1 _~  |
%% 60
                < a' g' d' a' c' f' a' e' > 4 _~ < a' g' d' a' c' f' a' e' a' > _~ < g' e' d'' d' a' c' f' a' a' > _~ < e' d' a' c' f' a' a' d'' a' > _~  |
                < g' d' a' c' f' a' bes a' d'' a' d' > 2. _~ < g' d' a' c' f' a' bes a' d'' a' d' f' > 4 _~  |
                < a' d'' d' f' bes g' d' a' > 4 _~ < d'' a' f' d' f' bes g' d' > _~ < a' g' d' a' f' d' f' bes > _~ < g' d' bes f' a' f' d' f' > _~  |
                < g' d' bes d' e' f' a' f' f' > 1 _~  |
                < d' d' e' f' a' f' f' d' a' > 4 _~ < d' d' e' f' a' f' f' d' a' a' > _~ < f' d' e' d' a' a' d'' f' a' f' > _~ < d' e' d' a' d'' f' a' f' a' a' > _~  |
%% 65
                < f' a' a' a' d' g' bes d'' d' a' f' > 4 _~ < a' d' a' f' a' a' d' g' bes d'' > _~ < d' a' f' a' a' bes d'' g c' d' g' e' > _~ < bes d'' d' g' c' f' g c' e' a > _~  |
                < d' g' a d' c' f' g c' e' a > 1 _~  |
                < g c' e' c' f' a a d' > 1 _~  |
                < g c' e' c' f' a a d' a d' > 4 _~ < g c' e' c' f' a a d' a d' e' > _~ < f' e' e' c' f' a a d' a d' > _~ < f' e' e' c' f' a a d' a d' g' > _~  |
                < c' f' a a d' e' f' a d' g' a' > 4 _~ < a d' a e' f' a d' g' a' > _~ < a f' a' d' e' f' a d' g' a' > _~ < e' f' a d' a' f' a' d' g' > 64 _~ < e' e' f' a d' a' f' a' d' g' g' > 4 _~  |
%% 70
                < g' e' f' e' a' g' c' f' a' f' a' d' > 2 _~ < g' e' f' e' a' g' c' f' a' f' a' d' a' > 4 _~ < e' f' e' a' a' f' a' d' g' c' f' a' > _~  |
                < f' a' d' e' a' g' c' f' a' a' f' > 4 _~ < f' a' d' e' a' g' c' f' a' a' f' a' > _~ < g' bes' ees' e' a' c' f' a' a' f' a' > _~ < bes' ees' e' a' c' f' a' f' a' c'' a' > _~  |
                < a' a' bes' ees' c' f' a' f' f' bes' d' c'' > 2 _~ < a' bes' ees' c' f' a' f' d' c'' a' f' bes' > 4 _~ < a' bes' ees' c' f' a' f' d' c'' a' f' bes' e' g' > _~  |
                < c'' a' bes' ees' a' e' d' a' f' bes' e' g' cis' > 2. _~ < a' bes' ees' a' e' d' f' bes' cis' a' e' g' > 4 _~  |
                < a' e' f' bes' d' cis' a' e' g' > 4 _~ < a' e' f' bes' d' cis' a' e' g' e' > _~ < f' a' e' f' bes' d' cis' a' e' g' e' > _~ < g' f' a' e' f' bes' d' cis' a' e' g' e' > _~  |
%% 75
                < a' a' e' f' g' d' cis' e' g' e' c' f' a' > 2 _~ < e' g' d' a' e' f' g' d' cis' e' c' f' a' a' bes > 4 _~ < d' a' e' f' g' d' cis' c' f' a' a' bes g' e' > _~  |
                < e' f' g' d' c' f' a' d' f' a' a' bes g' > 4 _~ < f' g' d' c' f' a' a' a' bes g' d' f' > _~ < f' g' d' c' f' a' a' a' bes g' d' f' a' > 2 _~  |
                < a' bes d' a' g' d' f' a' a' f' > 4 _~ < a' bes d' a' g' d' f' a' a' f' a' > _~ < g' bes' ees' d' a' d' f' a' a' f' a' > _~ < bes' ees' d' a' d' f' a' f' a' c'' a' > _~  |
                < a' a' bes' ees' f' d' f' a' f' d' bes' c'' > 2 _~ < a' bes' ees' f' d' f' a' f' bes' c'' a' d' > 4 _~ < a' bes' ees' f' d' f' a' f' bes' c'' a' d' e' g' > _~  |
                < c'' a' bes' ees' f' bes' a' d' e' g' c' f' a' > 2. _~ < a' bes' ees' f' bes' d' c' f' a' a' e' g' > 4 _~  |
%% 80
                < a' f' d' e' g' a' d' c' f' a' > 4 _~ < a' f' d' e' g' a' d' c' f' a' a' > _~ < d'' f' d' d' c' f' a' e' g' a' a' > _~ < d'' f' d' d' c' f' a' e' g' a' a' a' > _~  |
                < e' g' d'' d' d' c' f' a' a' a' a' bes g' > 2. _~ < d'' d' d' c' f' a' a' g' f' a' a' bes > 4 _~  |
                < d'' d' a' d' g' f' a' a' bes > 4 _~ < d'' d' a' d' g' f' a' a' bes f' > _~ < d'' d' a' d' g' f' a' a' bes f' a' > _~ < d'' d' a' d' g' f' a' a' bes f' a' f' > _~  |
                < a' d'' d' a' bes f' a' f' e' d' g' f' > 4 _~ < d'' d' e' d' g' f' a' bes f' a' f' > 2. _~  |
                < a' g' bes f' a' f' a' d' e' d' d' f' > 4 _~ < g' bes d' f' a' f' a' f' a' d' e' d' > _~ < f' bes a' f' a' f' a' d' e' d' d'' d' > _~ < bes d'' d' a' a' f' a' f' a' d' e' d' > _~ < d' d' e' d' d'' a' a' f' a' f' a' > 64 _~  |
%% 85
                < f' d' a' f' a' bes d' g' e' d' d'' a' a' > 4 _~ < d' a' d' d'' a' a' f' a' bes d' g' e' > _~ < d' f' a' bes d' g' e' g c' e' d'' a' a' > _~ < a' e' d'' a' a c' f' bes d' g' g c' e' a' > _~  |
                < bes d' g' a d' g c' e' a' a c' f' > 1 _~  |
                < a d' g c' e' a c' f' a' > 2 _~ < a c' f' a' > 4  |
                \bar "|."
            } % Voice
        >> % Staff ends

        \context Staff = "track 2, Other Stuff" << 
            \set Staff.instrumentName = \markup { \center-column { "Other Stuff " } }
            \set Staff.midiInstrument = "Acoustic Grand Piano"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \set Staff.autoBeaming = ##f % turns off all autobeaming

            \context Voice = "voice 2" {
                % Segment: 
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1
                \once \override Staff.TimeSignature #'style = #'() 
                \time 2/2
                
                \clef "bass"
                < f d > 1 _~  |
                < d f > 2 _~ < bes, f > _~  |
                f, 1  |
                < d f > 2 _~ < f c > 4 _~ < c a, > _~  |
%% 5
                < a, bes, > 2. _~ < e bes, > 4 _~  |
                < bes, e a, > 2 _~ < e a, > 4.. _~ < e a, > 16 _~  |
                                \once \override Staff.TimeSignature #'style = #'() 
                \time 2/4
                R2  |
                                \once \override Staff.TimeSignature #'style = #'() 
                \time 2/2
                < f d > 1 _~  |
                < d f > 2 _~ < bes, f > _~  |
%% 10
                f, 1  |
                < d f > 2 _~ < f c > 4 _~ < c a, > _~  |
                < a, bes, > 2. _~ < e bes, > 4 _~  |
                < bes, e a, > 2 _~ < e a, > 4.. _~ < e a, > 16 _~  |
                < bes, f > 1  |
%% 15
                f, 2 g,  |
                < d, d > 1  |
                < d f > 2 _~ < f c > 4 _~ < a, c >  |
                < f bes, > 2. _~ < e bes, > 4 _~  |
                < f f, > 1 _~ r64 < f f, > 16 _~  |
%% 20
                < fis, d > 1  |
                < g, d > 1  |
                < a f d > 2. _~ < bes f d > 4 _~  |
                < c' g c > 1 _~ r64 < c' g c > 16 _~  |
                < f, d > 1 _~  |
%% 25
                < g, d > 2 c 4 a,  |
                < d, d f > 1 _~  |
                \skip 4 \skip 8 \skip 16 r64 < d, d f > 16 r2  |
                < f d > 1 _~  |
                < d f > 2 _~ < bes, f > _~  |
%% 30
                f, 1  |
                < d f > 2 _~ < f c > 4 _~ < c a, > _~  |
                < a, bes, > 2. _~ < e bes, > 4 _~  |
                < bes, e a, > 2 _~ r64 < e a, > 16 _~ 
                % warning: bar too short, padding with rests
                % 120960 + 2220 < 124800  &&  37/64 < 2/2
                r64 r32 r8 r4  |
                < bes, f > 1  |
%% 35
                f, 2 g,  |
                < d, d > 1  |
                < d f > 2 _~ < f c > 4 _~ < a, c >  |
                < f bes, > 2. _~ < e bes, > 4 _~  |
                < f f, > 1 _~ r64 < f f, > 16 _~  |
%% 40
                < fis, d > 1  |
                < g, d > 1  |
                < a f d > 2. _~ < bes f d > 4 _~  |
                < c' g c > 1 _~ r64 < c' g c > 16 _~  |
                < f, d > 1 _~  |
%% 45
                < g, d > 2 c 4 a,  |
                < d, d f > 1 _~  |
                \skip 4 \skip 8 \skip 16 r64 < d, d f > 16 r2  |
                < f d > 1 _~  |
                < d f > 2 _~ < bes, f > _~  |
%% 50
                f, 1  |
                < d f > 2 _~ < f c > 4 _~ < c a, > _~  |
                < a, bes, > 2. _~ < e bes, > 4 _~  |
                < bes, e a, > 2 _~ r64 < e a, > 16 _~ 
                % warning: bar too short, padding with rests
                % 197760 + 2220 < 201600  &&  37/64 < 2/2
                r64 r32 r8 r4  |
                < bes, f > 1  |
%% 55
                f, 2 g,  |
                < d, d > 1  |
                < d f > 2 _~ < f c > 4 _~ < a, c >  |
                < f bes, > 2. _~ < e bes, > 4 _~  |
                < f f, > 1 _~ r64 < f f, > 16 _~  |
%% 60
                < fis, d > 1  |
                < g, d > 1  |
                < a f d > 2. _~ < bes f d > 4 _~  |
                < c' g c > 1 _~ r64 < c' g c > 16 _~  |
                < f, d > 1 _~  |
%% 65
                < g, d > 2 c 4 a,  |
                < d, d f > 1 _~  |
                \skip 4 \skip 8 \skip 16 r64 < d, d f > 16 r2  |
                < f d > 1 _~  |
                < d f > 2 _~ < bes, f > _~  |
%% 70
                f, 1  |
                < d f > 2 _~ < f c > 4 _~ < c a, > _~  |
                < a, bes, > 2. _~ < e bes, > 4 _~  |
                < bes, e a, > 2 _~ r64 < e a, > 16 _~ 
                % warning: bar too short, padding with rests
                % 274560 + 2220 < 278400  &&  37/64 < 2/2
                r64 r32 r8 r4  |
                < bes, f > 1  |
%% 75
                f, 2 g,  |
                < d, d > 1  |
                < d f > 2 _~ < f c > 4 _~ < a, c >  |
                < f bes, > 2. _~ < e bes, > 4 _~  |
                < f f, > 1 _~ r64 < f f, > 16 _~  |
%% 80
                < fis, d > 1  |
                < g, d > 1  |
                < a f d > 2. _~ < bes f d > 4 _~  |
                < c' g c > 1 _~ r64 < c' g c > 16 _~  |
                < f, d > 1 _~  |
%% 85
                < g, d > 2 c 4 a,  |
                < d, d f > 1 
                % warning: overlong bar truncated here |
            } % Voice
        >> % Staff (final) ends

    >> % notes

    \layout {
        indent = 3.0\cm
        short-indent = 1.5\cm
        \context { \Staff \RemoveEmptyStaves }
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
%         \midi {
%         } 
} % score
