% This LilyPond file was generated by Rosegarden 15.12
\include "nederlands.ly"
\version "2.12.0"
\header {
    arranger = "D. Michael McIntyre"
    composer = "L. V. Beethoven (1770-1827)"
    copyright = "Copyright © 2008 D. Michael McIntyre"
    opus = "Op. 72b"
    piece = "Fidelio Overture"
    title = "Staff Brackets"
    tagline = "Created using Rosegarden 15.12 and LilyPond"
}
#(set-global-staff-size 18)
#(set-default-paper-size "a4")
global = { 
    \time 2/2
    \skip 1*3 
}
globalTempo = {
    \override Score.MetronomeMark #'transparent = ##t
    \tempo 4 = 120  
}
\score {
    << % common
        \context StaffGroup = "0" << 
            % Force offset of colliding notes in chords:
            \override Score.NoteColumn #'force-hshift = #1.0
            % Allow fingerings inside the staff (configured from export options):
            \override Score.Fingering #'staff-padding = #'()

            \context Staff = "track 2, 2 Flauti" << 
                \set Staff.instrumentName = \markup { \center-column { "2 Flauti " } }
                \set Staff.midiInstrument = "Flute"
                \set Score.skipBars = ##t
                \set Staff.printKeyCancellation = ##f
                \new Voice \global
                \new Voice \globalTempo

                \context Voice = "voice 1" {
                    % Segment: Flute
                    \override Voice.TextScript #'padding = #2.0
                    \override MultiMeasureRest #'expand-limit = 1
                    \time 2/2
                    
                    \clef "treble"
                    \key e \major
                    e'' 4. b' 8 b' 4 -\staccato r  |
                    gis'' 4. e'' 8 e'' 4 -\staccato r  |
                    R1  |
                    \bar "|."
                } % Voice
            >> % Staff ends

            \context Staff = "track 3, 2 Oboi" << 
                \set Staff.instrumentName = \markup { \center-column { "2 Oboi " } }
                \set Staff.midiInstrument = "Oboe"
                \set Score.skipBars = ##t
                \set Staff.printKeyCancellation = ##f
                \new Voice \global
                \new Voice \globalTempo

                \context Voice = "voice 2" {
                    % Segment: Oboe
                    \override Voice.TextScript #'padding = #2.0
                    \override MultiMeasureRest #'expand-limit = 1
                    \time 2/2
                    
                    \clef "treble"
                    \key e \major
                    e'' 4. b' 8 b' 4 -\staccato r  |
                    gis'' 4. e'' 8 e'' 4 -\staccato r  |
                    R1  |
                    \bar "|."
                } % Voice
            >> % Staff ends

            \context Staff = "track 4, 2 Clarinetti in A" << 
                \set Staff.instrumentName = \markup { \center-column { "2 Clarinetti in A " \line { "in A" } } }
                \set Staff.midiInstrument = "Clarinet"
                \set Score.skipBars = ##t
                \set Staff.printKeyCancellation = ##f
                \new Voice \global
                \new Voice \globalTempo

                \context Voice = "voice 3" {
                    % Segment: A clarinet
                    \override Voice.TextScript #'padding = #2.0
                    \override MultiMeasureRest #'expand-limit = 1
                    \time 2/2
                    
                    \clef "treble"
                    \key g \major
                    g'' 4. d'' 8 d'' 4 -\staccato r  |
                    < b'' b' > 4. < g'' g' > 8 < g'' g' > 4 -\staccato r  |
                    R1  |
                    \bar "|."
                } % Voice
            >> % Staff ends

            \context Staff = "track 5, 2 Fagotti" << 
                \set Staff.instrumentName = \markup { \center-column { "2 Fagotti " } }
                \set Staff.midiInstrument = "Bassoon"
                \set Score.skipBars = ##t
                \set Staff.printKeyCancellation = ##f
                \new Voice \global
                \new Voice \globalTempo

                \context Voice = "voice 4" {
                    % Segment: Bassoon
                    \override Voice.TextScript #'padding = #2.0
                    \override MultiMeasureRest #'expand-limit = 1
                    \time 2/2
                    
                    \clef "bass"
                    \key e \major
                    R1*3  |
                    \bar "|."
                } % Voice
            >> % Staff ends
        >> % StaffGroup 1
        \context StaffGroup = "2" <<
            \context GrandStaff = "1" <<

                \context Staff = "track 7, Corni in E I II" << 
                    \set Staff.instrumentName = \markup { \center-column { "Corni in E I II " \line { "in E" } } }
                    \set Staff.midiInstrument = "French Horn"
                    \set Score.skipBars = ##t
                    \set Staff.printKeyCancellation = ##f
                    \new Voice \global
                    \new Voice \globalTempo

                    \context Voice = "voice 5" {
                        % Segment: French horn in E {
                        \override Voice.TextScript #'padding = #2.0
                        \override MultiMeasureRest #'expand-limit = 1
                        \time 2/2
                        
                        \clef "treble"
                        \key c \major
                        R1*3  |
                        \bar "|."
                    } % Voice
                >> % Staff ends

                \context Staff = "track 8, III IV" << 
                    \set Staff.instrumentName = \markup { \center-column { "III IV " \line { "in E" } } }
                    \set Staff.midiInstrument = "French Horn"
                    \set Score.skipBars = ##t
                    \set Staff.printKeyCancellation = ##f
                    \new Voice \global
                    \new Voice \globalTempo

                    \context Voice = "voice 6" {
                        % Segment: French horn in E }
                        \override Voice.TextScript #'padding = #2.0
                        \override MultiMeasureRest #'expand-limit = 1
                        \time 2/2
                        
                        \clef "treble"
                        \key c \major
                        R1*3  |
                        \bar "|."
                    } % Voice
                >> % Staff ends
            >> % GrandStaff 1

            \context Staff = "track 9, 2 Trombe in C" << 
                \set Staff.instrumentName = \markup { \center-column { "2 Trombe in C " } }
                \set Staff.midiInstrument = "Trumpet"
                \set Score.skipBars = ##t
                \set Staff.printKeyCancellation = ##f
                \new Voice \global
                \new Voice \globalTempo

                \context Voice = "voice 7" {
                    % Segment: Trumpet in C
                    \override Voice.TextScript #'padding = #2.0
                    \override MultiMeasureRest #'expand-limit = 1
                    \time 2/2
                    
                    \clef "treble"
                    \key e \major
                    R1*3  |
                    \bar "|."
                } % Voice
            >> % Staff ends
            \context GrandStaff = "2" <<

                \context Staff = "track 10, Trombone Tenore" << 
                    \set Staff.instrumentName = \markup { \center-column { "Trombone Tenore " } }
                    \set Staff.midiInstrument = "Trombone"
                    \set Score.skipBars = ##t
                    \set Staff.printKeyCancellation = ##f
                    \new Voice \global
                    \new Voice \globalTempo

                    \context Voice = "voice 8" {
                        % Segment: Tenor trombone {
                        \override Voice.TextScript #'padding = #2.0
                        \override MultiMeasureRest #'expand-limit = 1
                        \time 2/2
                        
                        \clef "tenor"
                        \key e \major
                        R1*3  |
                        \bar "|."
                    } % Voice
                >> % Staff ends

                \context Staff = "track 11, Trombone Basso" << 
                    \set Staff.instrumentName = \markup { \center-column { "Trombone Basso " } }
                    \set Staff.midiInstrument = "Trombone"
                    \set Score.skipBars = ##t
                    \set Staff.printKeyCancellation = ##f
                    \new Voice \global
                    \new Voice \globalTempo

                    \context Voice = "voice 9" {
                        % Segment: Bass trombone   }
                        \override Voice.TextScript #'padding = #2.0
                        \override MultiMeasureRest #'expand-limit = 1
                        \time 2/2
                        
                        \clef "bass"
                        \key e \major
                        R1*3  |
                        \bar "|."
                    } % Voice
                >> % Staff ends
            >> % GrandStaff 2
        >> % StaffGroup 2
        \context StaffGroup = "3" <<

            \context Staff = "track 13, Timpani in E-H" << 
                \set Staff.instrumentName = \markup { \center-column { "Timpani in E-H " } }
                \set Staff.midiInstrument = "Timpani"
                \set Score.skipBars = ##t
                \set Staff.printKeyCancellation = ##f
                \new Voice \global
                \new Voice \globalTempo

                \context Voice = "voice 10" {
                    % Segment: Timpani
                    \override Voice.TextScript #'padding = #2.0
                    \override MultiMeasureRest #'expand-limit = 1
                    \time 2/2
                    
                    \clef "bass"
                    \key e \major
                    R1*3  |
                    \bar "|."
                } % Voice
            >> % Staff ends
        >> % StaffGroup 3
        \context StaffGroup = "4" <<
            \context GrandStaff = "3" <<

                \context Staff = "track 15, Violino I" << 
                    \set Staff.instrumentName = \markup { \center-column { "Violino I " } }
                    \set Staff.midiInstrument = "Violin"
                    \set Score.skipBars = ##t
                    \set Staff.printKeyCancellation = ##f
                    \new Voice \global
                    \new Voice \globalTempo

                    \context Voice = "voice 11" {
                        % Segment: Violin {
                        \override Voice.TextScript #'padding = #2.0
                        \override MultiMeasureRest #'expand-limit = 1
                        \time 2/2
                        
                        \clef "treble"
                        \key e \major
                        R1*3  |
                        \bar "|."
                    } % Voice
                >> % Staff ends

                \context Staff = "track 16, Violino II" << 
                    \set Staff.instrumentName = \markup { \center-column { "Violino II " } }
                    \set Staff.midiInstrument = "Violin"
                    \set Score.skipBars = ##t
                    \set Staff.printKeyCancellation = ##f
                    \new Voice \global
                    \new Voice \globalTempo

                    \context Voice = "voice 12" {
                        % Segment: Violin }
                        \override Voice.TextScript #'padding = #2.0
                        \override MultiMeasureRest #'expand-limit = 1
                        \time 2/2
                        
                        \clef "treble"
                        \key e \major
                        R1*3  |
                        \bar "|."
                    } % Voice
                >> % Staff ends
            >> % GrandStaff 3

            \context Staff = "track 17, Viola" << 
                \set Staff.instrumentName = \markup { \center-column { "Viola " } }
                \set Staff.midiInstrument = "Viola"
                \set Score.skipBars = ##t
                \set Staff.printKeyCancellation = ##f
                \new Voice \global
                \new Voice \globalTempo

                \context Voice = "voice 13" {
                    % Segment: Viola
                    \override Voice.TextScript #'padding = #2.0
                    \override MultiMeasureRest #'expand-limit = 1
                    \time 2/2
                    
                    \clef "alto"
                    \key e \major
                    R1*3  |
                    \bar "|."
                } % Voice
            >> % Staff ends
            \context GrandStaff = "4" <<

                \context Staff = "track 18, Violoncello" << 
                    \set Staff.instrumentName = \markup { \center-column { "Violoncello " } }
                    \set Staff.midiInstrument = "Cello"
                    \set Score.skipBars = ##t
                    \set Staff.printKeyCancellation = ##f
                    \new Voice \global
                    \new Voice \globalTempo

                    \context Voice = "voice 14" {
                        % Segment: Violoncello {
                        \override Voice.TextScript #'padding = #2.0
                        \override MultiMeasureRest #'expand-limit = 1
                        \time 2/2
                        
                        \clef "bass"
                        \key e \major
                        R1*3  |
                        \bar "|."
                    } % Voice
                >> % Staff ends

                \context Staff = "track 19, Contrabasso" << 
                    \set Staff.instrumentName = \markup { \center-column { "Contrabasso " } }
                    \set Staff.midiInstrument = "Contrabass"
                    \set Score.skipBars = ##t
                    \set Staff.printKeyCancellation = ##f
                    \new Voice \global
                    \new Voice \globalTempo

                    \context Voice = "voice 15" {
                        % Segment: Contrabass }
                        \override Voice.TextScript #'padding = #2.0
                        \override MultiMeasureRest #'expand-limit = 1
                        \time 2/2
                        
                        \clef "bass_8"
                        \key e \major
                        R1*3  |
                        \bar "|."
                    } % Voice
                >> % Staff (final) ends
            >> % GrandStaff (final) 4
        >> % StaffGroup (final) 4

    >> % notes

    \layout {
        indent = 3.0\cm
        short-indent = 1.5\cm
        \context { \Staff \RemoveEmptyStaves }
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
%         \midi {
%         } 
} % score
