% This LilyPond file was generated by Rosegarden 26.06
\include "nederlands.ly"
\version "2.18.0"
\header {
    title = "Testcase for grace notes and ties"
    tagline = "Created using Rosegarden 26.06 and LilyPond"
}
#(set-global-staff-size 18)
#(set-default-paper-size "a4")
global = { 
    \time 4/4
    \skip 1*3 
}
globalTempo = {
    \override Score.MetronomeMark.transparent = ##t
    \tempo 4 = 120  
}
\score {
    << % common
        % Force offset of colliding notes in chords:
        \override Score.NoteColumn.force-hshift = #1.0
        % Allow fingerings inside the staff (configured from export options):
        \override Score.Fingering.staff-padding = #'()

        \context Staff = "track 1" << 
            \set Staff.midiInstrument = "Acoustic Grand Piano"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \set Staff.autoBeaming = ##f % turns off all autobeaming

            \context Voice = "voice 0.0" {
                % Segment: Acoustic Grand Piano
                \override Voice.TextScript.padding = #2.0
                \override MultiMeasureRest.expand-limit = 1
                \once \override Staff.TimeSignature.style = #'numbered 
                \time 4/4
                
                \clef "treble"
                \key c \major
                R1  |
                \grace { e' 16 [ g' ] } d'' 8 [ e'' c'' b' ] g' [ \grace { e' 16 } d'' 8 ] r4  |
                \grace { e' 16 [ g' ] } g' 8 [ b' d'' f'' ] r2 
                \bar "|."
            } % Voice

            % End of segment Acoustic Grand Piano

            % End voice 0
        >> % Staff ends

    >> % notes

    \layout {
        \context { \Staff \RemoveEmptyStaves }
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
%         \midi {
%         } 
} % score
