% This LilyPond file was generated by Rosegarden 15.12
\include "nederlands.ly"
\version "2.12.0"
\header {
    copyright =  \markup { "Copyright "\char ##x00A9" xxxx Copyright Holder" }
    subtitle = "not yet subtitled"
    title = "Not Yet Titled"
    tagline = "Created using Rosegarden 15.12 and LilyPond"
}
#(set-global-staff-size 18)
#(set-default-paper-size "a4")
global = { 
    \time 4/4
    \skip 1*6 
}
globalTempo = {
    \override Score.MetronomeMark #'transparent = ##t
    \tempo 4 = 120  
}
\score {
    << % common
        % Force offset of colliding notes in chords:
        \override Score.NoteColumn #'force-hshift = #1.0
        % Allow fingerings inside the staff (configured from export options):
        \override Score.Fingering #'staff-padding = #'()

        \context Staff = "track 1" << 
            \set Staff.midiInstrument = "String Ensemble 1"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \set Staff.autoBeaming = ##f % turns off all autobeaming

            \context Voice = "voice 1" {
                % Segment: 4
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1
                \time 4/4
                
                \clef "treble"
                \key c \major
                r8 r16 g' r8 g c' g r g  |
                c' 8 g r g c' g c' g  |
                c' 2 r  |
            } % Voice

            \context Voice = "voice 2" {
                % Segment: 3
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1
                \time 4/4
                
                \clef "treble"
                \key c \major
                r8 e' r b c' b r b  |
                c' 8 b r b c' b c' b  |
                g 2 r  |
            } % Voice

            \context Voice = "voice 3" {
                % Segment: 2
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1
                \time 4/4
                
                \clef "treble"
                \key c \major
                r16 d' r8 r f' c' f' r f'  |
                c' 8 f' r f' c' f' c' f'  |
                e' 2 r  |
            } % Voice

            \context Voice = "voice 4" {
                % Segment: 1
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1
                \time 4/4
                
                \clef "treble"
                \key c \major
                c' 4 c' 8 d' c' d' c' d'  |
                c' 8 d' c' d' c' d' c' d'  |
                c' 2 r  |
            } % Voice
        >> % Staff ends

        \context Staff = "track 2" << 
            \set Staff.midiInstrument = "Trumpet"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \set Staff.autoBeaming = ##f % turns off all autobeaming

            \context Voice = "voice 5" {
                % Segment: Trumpet
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*3 
                \clef "treble"
                \key c \major
                c'' 1 _~  |
%% 5
                c'' 1 _~  |
                c'' 1  |
                \bar "|."
            } % Voice

            \context Voice = "voice 6" {
                % Segment: Trumpet
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*3 
                \clef "treble"
                \key c \major
                c' 1 _~  |
%% 5
                c' 1 _~  |
                c' 1  |
                \bar "|."
            } % Voice
        >> % Staff ends

        \context Staff = "track 4" << 
            \set Staff.midiInstrument = "Honky-tonk Piano"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \set Staff.autoBeaming = ##f % turns off all autobeaming

            \context Voice = "voice 7" {
                % Segment: On fixed channel
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*2 
                \clef "treble"
                \key c \major
                c' 8 [ d' e' f' ] e' [ g' b' d'' ]  |
            } % Voice

            \context Voice = "voice 8" {
                % Segment: On fixed channel
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*2 
                \clef "treble"
                \key c \major
                e' 8 [ f' g' f' ] e' [ g' b' d'' ]  |
            } % Voice
        >> % Staff (final) ends

    >> % notes

    \layout {
        \context { \Staff \RemoveEmptyStaves }
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
%         \midi {
%         } 
} % score
