% This LilyPond file was generated by Rosegarden 15.12
\include "nederlands.ly"
\version "2.12.0"
#(set-global-staff-size 18)
#(set-default-paper-size "a4")
global = { 
    \time 4/4
    \skip 1*3 
}
\score {
    << % common
        % Force offset of colliding notes in chords:
        \override Score.NoteColumn #'force-hshift = #1.0
        % Allow fingerings inside the staff (configured from export options):
        \override Score.Fingering #'staff-padding = #'()

        \context Staff = "track 1, untitled" << 
            \set Staff.instrumentName = \markup { \center-column { "untitled " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global

            \context Voice = "voice 1" {
                % Segment: 
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1
                \time 4/4
                
                \times 2/3 { cis' 8 b cis' } \times 2/3 { cis' b 4 } \times 2/3 { b 8 ees' r } \times 2/3 { r b 4 }  |
                \times 2/3 { r8 r4 } \times 2/3 { cis' 8 r cis' } \times 2/3 { b 4 cis' 8 } \times 2/3 { fis'' aes'' e' }  |
            } % Voice
        >> % Staff ends

        \context Staff = "track 2, untitled" << 
            \set Staff.instrumentName = \markup { \center-column { "untitled " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global

            \context Voice = "voice 2" {
                % Segment: 
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1
                \time 4/4
                
                cis' 8 [ b cis' cis' ] cis' [ b 4 cis' 8 ]  |
                cis' 16 [ b cis' r ] cis' [ b 8 cis' 16 ] cis' 8 [ r16 cis' 8 ] e' 16 [ b 8 ]  |
                a'' 16 [ g'' 32 a'' 16 g'' 32 r16 ] a'' [ g'' 8 a'' 16 ] a'' 8 [ r16 a'' 8 ] c''' 16 [ g'' 8 ]  |
                \bar "|."
            } % Voice
        >> % Staff (final) ends

    >> % notes

    \layout {
        indent = 3.0\cm
        short-indent = 1.5\cm
        \context { \Staff \RemoveEmptyStaves }
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
%         \midi {
%         } 
} % score
